### ISSUE TITLE
[1.181011.0] No guild member names in specific sheets.

### ISSUE THREAD

**Issue by Bartek83** [PopGoesTheWza/swgoh-tb-sheets#13]
✖ USAGE QUESTIONS → Use these dedicated resources:
      Docs - [Instructions Manual](https://docs.google.com/document/d/1InDnFdYdlRDpejeiFkGi6HxMEWmBbfX_wAvWRf1MCME/edit?usp=sharing)
      Discord server - https://discord.gg/ywzJEaQ

✔ Enhancements → Be specific. Suggest implementation when possible.
✔ BUGS → ❤❤❤. Keep in mind some bugs may not be immediately fixable.

### Steps to reproduce
I followed the instructions and put my guild swgoh.gg link in the Meta tab. Then followed the instructions to load the guild data into it. Everything is fine except no guild names are loaded into 1 row of LS Missions, DS Missions and Exclusions sheets. All the cells still display "Member Name". This isn't the issue with TB, Heroes and Ship sheets

### Expected Result
Expected to change "Member Name" to actual names of the guild members

### Actual Result
No change of the names in first row of LS Missions, DS Missions and Exclusions sheets after successfully refreshing the TB
### Version
v1.181016.0

### Testcase
Link to my copy of a spreadsheet. Editing enabled if needed:
https://docs.google.com/spreadsheets/d/1REOuL68W98RZZPApBvdC85yX00fx5gh_M_dluDkDjMc/edit?usp=sharing

**Comment by PopGoesTheWza** [comment]
@Bartek83
This is WAD (Work As Designed)

On the Meta tab is a field for the I’d of your own copy of the [Exclusions and Missions spreadsheet](https://docs.google.com/spreadsheets/d/1ta7OriYavi9Re9T-CUTEkRJ3UfnKs17LrrzWW8Dm_zo/edit?usp=sharing) which you have to maintain manually.

The principle is that the main spreadsheet is only shared between guild officers, while the Exclusions and Missions spreadsheet is shared to everyone in the guild.

Does this answer your issue?
