### ISSUE TITLE
WhatsApp vinculation

### ISSUE THREAD

**Issue by GRAVEDDIGER** [PopGoesTheWza/swgoh-tb-sheets#14]
Hello I'm working on the sheet to provide a new option. I'm building a tab in which every member can create a column next to the alias of the member and write the contact information of his fone so I can make an algorithm that builds me a string with the @s for WhatsApp users.
So I upload a PDF of the sheet and paste the string and it's done everyone is notified
And am also wrote an algorithm that takes the info provided for the for recognition algorithm of echobase and pull it to the sheet so that fixes the problem of cases 4/6.

**Comment by PopGoesTheWza** [comment]
@GRAVEDDIGER Hi,
I am not sure what you are suggesting? To integrate your developments into the template?

**Comment by PopGoesTheWza** [comment]
@GRAVEDDIGER Please provide comment/feedback. Otherwise I will simply close this issue.

**Comment by PopGoesTheWza** [comment]
@GRAVEDDIGER No response in one month. I'm closing this issue
