### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by DarkPhoenixSniper** [PopGoesTheWza/swgoh-tb-sheets#15]
On the Search Units sheet. Make it so we can Sort Ascending or Descending depending on a cell. For Heroes and Ships separately. 

✖ USAGE QUESTIONS → Use these dedicated resources:
      Docs - [Instructions Manual](https://docs.google.com/document/d/1InDnFdYdlRDpejeiFkGi6HxMEWmBbfX_wAvWRf1MCME/edit?usp=sharing)
      Discord server - https://discord.gg/ywzJEaQ

✔ Enhancements → Be specific. Suggest implementation when possible.
✔ BUGS → ❤❤❤. Keep in mind some bugs may not be immediately fixable.

### Title (Put in field above)
Use the format: [version] Short description
i.e. [1.181011.0] On tab "Search Units" sort order is wrond

### Version
x.y.z

### Testcase
Provide a link to a copy of the TB Sheets if necessary

**Comment by PopGoesTheWza** [comment]
@DarkPhoenixSniper Will be in next release.

**Comment by PopGoesTheWza** [comment]
@DarkPhoenixSniper shipped with last release.
