### ISSUE TITLE
[1.181016.0] Slots in the micromanage webhooks

### ISSUE THREAD

**Issue by Volet12** [PopGoesTheWza/swgoh-tb-sheets#16]
The Slots in webhooks are not working 

![przechwytywanie](https://user-images.githubusercontent.com/44255597/47138501-e1919f80-d2b9-11e8-80f8-3839746d2245.PNG)

Everything works well in the Version: 1.180704.1

![przechwytywanie](https://user-images.githubusercontent.com/44255597/47138473-c3c43a80-d2b9-11e8-99f2-0d9f4af49fef.PNG)

**Comment by PopGoesTheWza** [comment]
@Volet12 I will add an option to switch slot display

**Comment by PopGoesTheWza** [comment]
@Volet12 enhancement shipped with latest release.
