### ISSUE TITLE
[1.181019.0] Search Units Bug

### ISSUE THREAD

**Issue by DarkPhoenixSniper** [PopGoesTheWza/swgoh-tb-sheets#17]
Search Units tab

If the user in Column K does not have a Character or Ship unlocked, if you sort Descending on that character, they will show up at the top of the list as Empty.  

If that member has it unlocked, it shows correctly.

**Comment by PopGoesTheWza** [comment]
Strange edge case which is no longer happening on my copies (from same template version).
Investigating...

**Comment by PopGoesTheWza** [comment]
Formula fixed in the template.
