### ISSUE TITLE
ENHANCEMENT - Meta tab, When changing Filtering update Tag.

### ISSUE THREAD

**Issue by DarkPhoenixSniper** [PopGoesTheWza/swgoh-tb-sheets#18]
When changing from Light to Dark Side, the tag should auto update to empire.
Same when going from Dark to Light, the tag should update to rebel.

**Comment by DarkPhoenixSniper** [comment]
Simple formula on Meta Tab in cell C2
=IF(B2=“”,,IF(B2=“Dark Side”,”empire”,”rebel”))

**Comment by PopGoesTheWza** [comment]
@DarkPhoenixSniper I am considering to simply remove the UI and adjust the code to deduce the relevant faction tag from the current alignment/side.

**Comment by PopGoesTheWza** [comment]
In testing. Schedule for next release.
![image](https://user-images.githubusercontent.com/32041843/47719338-1f43e000-dc4b-11e8-9304-58e97c39e455.png)
