### ISSUE TITLE
ENHANCEMENTS (MULTIPLE) - When changing from Light to Dark & vice versa

### ISSUE THREAD

**Issue by DarkPhoenixSniper** [PopGoesTheWza/swgoh-tb-sheets#19]
Maybe have a way of just updating the fields from Light to Dark for all tabs, without pulling data again from the servers?

E.g.  I just updated the sheet, but whoops it was Dark Side. Now I have to change the Meta tab, then rerun and get data again from the servers.  Shouldn't it just convert the sheets to dark.  Prompt Yes/No to Get new data from server?

Maybe even have an option on the Meta tab to timestamp when the script was last ran, and if rerunning  within lets say 30-60 minutes, NOT to check the servers for new data, unless a check box is checked.  

This might help in less stress and data calls to the servers.

**Comment by PopGoesTheWza** [comment]
This issue should be covered with completion of #20
