### ISSUE TITLE
Implement a one hour caching of roster data

### ISSUE THREAD

**Issue by PopGoesTheWza** [PopGoesTheWza/swgoh-tb-sheets#20]
The goal is to prevent hitting the data sources again and again while there is no new data.

Implementation design:
- use Google Cache services, with a one hour duration
- calculate a hash to detect significant change in settings which should invalidate caching (switching data source, changing guild Id/ally code, rename/add/remove settings on the roster tab)

With this feature, event switching (LS/DS), sort order, etc. can take place almost instantly by reusing the data already within the spreadsheet.

**Comment by DarkPhoenixSniper** [comment]
@PopGoesTheWza if you need to get a hold of me during the weekdays.  email me at darkphoenixsniper@gmail.com

**Comment by DarkPhoenixSniper** [comment]
@PopGoesTheWza I will work on recommended changes tonight/tomorrow for what i'm thinking of tracking
Obviously a timestamp, which I already provided, but also move up the swgoh.help api section and move the captured values down below in a row.
Timestamp, Light/Dark Side, rebel/empire, sort option, source option.
Capture this data and store on the META tab, during initial data pull (At the end of the scripts)

- If within an hour of last update, and nothing has changed. Prompt the user to pull new data? (Yes/No)

- If within an hour of last update, and Light/Dark, rebel/empire, or sort option has changed.  
Simply say converting from X to Y or Changing Sort option.  

- If changing sources, always pull new data (automatically on clicking refresh)

**Comment by PopGoesTheWza** [comment]
@DarkPhoenixSniper take a look at the swgoh help api code and how session token is handled…

**Comment by PopGoesTheWza** [comment]
@DarkPhoenixSniper I committed a 6 hours cache of units' common attributes (name, base id and tags) and a 1 hour cache of members and their units. Basic tests proved conclusive.
Likely to be in next release.

**Comment by PopGoesTheWza** [comment]
in next release
