### ISSUE TITLE
"Add Member" Column should have some form of validation to only accept digit input (no dashes)

### ISSUE THREAD

**Issue by skiadas** [PopGoesTheWza/swgoh-tb-sheets#27]
Currently there is no feedback whatsoever that you are doing something wrong when you put in an ally code as xxx-xxx-xxx instead of just the 9 digits. It would be nice if there was something there to either prevent it from happening or showing that something is wrong.  

A data validation requiring a number between 0 and 999999999 should do the trick.

**Comment by PopGoesTheWza** [comment]
@skiadas latest release has better formatting and data validation for ally codes (on Roster, Snapshot and Meta)

Please provide feedback

**Comment by skiadas** [comment]
@PopGoesTheWza Seems to work, on Roster. I don't use snapshots so i don't know about that one. Where does it show up in the Meta?

**Comment by PopGoesTheWza** [comment]
On the Meta tab, SwgohHelp configuration requires an ally code.

I will close this issue since the latest implementation seems satisfactory.
