### ISSUE TITLE
[1.181114.0] Platoon reset not clearing all units/formatting

### ISSUE THREAD

**Issue by DarkPhoenixSniper** [PopGoesTheWza/swgoh-tb-sheets#29]
### Steps to reproduce
Format not clearing...
Assign units to phase 4,5,6. Then click the Refresh icon to assign units, Rare units will be Blue or Red.
Now click on the Red X to reset, now on those cells that were Rare before.  The colors remain during input of unit. 

All units not clearing...
assign ships to phase 6.  Now when I choose phase 1, and then reset (Logically eliminating me changing to phase 1 and rerunning later, as the reset will also import phase 1 units.  In the Donating section H56+ I still see people donating, as they had Ship assignments.

### Expected Result
All formatting to reset to BLACK font, and all units from all platoons to properly clear.

**Comment by PopGoesTheWza** [comment]
Fixed. Will be included in next release.

**Comment by PopGoesTheWza** [comment]
Fixed in latest release
