### ISSUE TITLE
[Enhancement] Who has a Specific Unit Sheet

### ISSUE THREAD

**Issue by CyberShark98** [PopGoesTheWza/swgoh-tb-sheets#33]
Could you add a Who Has It? Sheet?

So on that sheet I would select say, Director Krennic from a drop down. Then it shows in the next column, all the ppl that have it.  

I would use that to copy to discord for instructions

thanks,

**Comment by PopGoesTheWza** [comment]
@CyberShark98 doesn't the `Search Unit` sheet already do that?

**Comment by CyberShark98** [comment]
Face Palm, apparently i'm dumb, yes it does... how did i never realize this... thank you!

**Comment by DarkPhoenixSniper** [comment]
Closing ticket, as Enhancement was already available within the sheet
