### ISSUE TITLE
[Enhancement] Clean up of sheets, new dash board

### ISSUE THREAD

**Issue by CyberShark98** [PopGoesTheWza/swgoh-tb-sheets#34]
There are so many tabs, I was thinking you could clean it up, especially for new ppl.

Move everything from the TB tab to a new sheet called Special Missions Analysis 

Leave the Refresh button there

Hide all sheets except
TB
Platoon
Meta
Instructions

Add a list of all hidden sheets, with brief description
Using check boxes, it unhides sheets when checked

**Comment by PopGoesTheWza** [comment]
Thinking about it. No design decided yet

**Comment by CyberShark98** [comment]
![TB Dashboard](https://user-images.githubusercontent.com/44117187/55670759-e50be980-584d-11e9-8e70-c2bb0b02fcc1.png)

**Comment by PopGoesTheWza** [comment]
Done in latest release
