### ISSUE TITLE
[1.190325.0] Discord Platoon Assignment Deployment Bug

### ISSUE THREAD

**Issue by DarkPhoenixSniper** [PopGoesTheWza/swgoh-tb-sheets#35]
### Steps to reproduce
LS TB Phase 3 and beyond.  Any with SHIPS.

### Expected Result
Deploy assignments to Discord with all information.

### Actual Result
Does not deploy ANYTHING to Discord.
Works fine if in Phase 1-2 as Ships are not available. Issue occurs on all phases with Ships.
Even having it 'SKIP' all Ship platoons, it still does not post assignments, as it is detecting the ship section.

### Test Case
Not needed, as current Template has same issue.

**Comment by PopGoesTheWza** [comment]
Done in last release
