### ISSUE TITLE
[1.190502.0] G13 undefined Bug

### ISSUE THREAD

**Issue by CyberShark98** [PopGoesTheWza/swgoh-tb-sheets#37]
### Steps to reproduce
Brendon
Today at 2:08 AM
Hi! The sheet can't sort the power of G13.

### Expected Result
not undefined
### Actual Result
undefined
### Testcase
https://media.discordapp.net/attachments/352950010150912000/595510983477166130/unknown.png

**Comment by DarkPhoenixSniper** [comment]
This seems to have corrected itself after the recent source updates

**Comment by CyberShark98** [comment]
Thanks!
