### ISSUE TITLE
[1.190502.0] Bug - Cannot account for 0 combat missions

### ISSUE THREAD

**Issue by CyberShark98** [PopGoesTheWza/swgoh-tb-sheets#38]
varthdaderToday at 9:32 AM
The sheet doesn't account for going 0/4 in missions (a real possibility especially the phases with 2 ship missions).  So, I updated mine to add a "Tier 0" column to the Estimates sheet and changed the offset part of the formula.  Rather inelegant, but gets the job done
https://docs.google.com/spreadsheets/d/1HYsT-zAbxd99gGglNmF2HtfJAUeBfplCrfw3chs1DXQ/edit?usp=sharing

**Comment by CyberShark98** [comment]
KoreToday at 10:33 AM
I was about to point this out.
there is no way to account for 0 CM waves completed due to failure
because of this little tid-bit: +Q23*OFFSET(J23,0,R23-1)
if R23 (the number of waves completed) is 0 then the offset is a -1 thus multiplying Q23 (the number of members) by whatever is in I23
in the case of this sheet, it happens to be the value of completing 4 waves :dizzy_face:
varthdaderToday at 10:44 AM
Yup, take a look at the sheet i posted as it corrects for this case
If @CyberShark or whoever is the "sheet master" wants to incorporate this change and repost for all
CyberSharkToday at 10:46 AM
@Volet can you check this out for your sheet? I'll pass the info on to Pops for the master sheet. Thanks @varthdader
varthdaderToday at 10:46 AM
Again, I took a quick and inelegant approach to address the zero case.  Not sure if anyone wants to do it better
CyberSharkToday at 10:47 AM
much appreciated either way :smiley:
KoreToday at 10:50 AM
another way to do it is to throw an IF in there that includes the OFFSET such that it returns a 0 if R23 is 0 and ignores the OFFSET; i hate adding columns for a constant, specifically a zero

**Comment by PopGoesTheWza** [comment]
Done in latest release
