### ISSUE TITLE
[1.181011.0] Webhooks (at least Rare by Units) display « undefined » in place of the list of rare by

### ISSUE THREAD

**Issue by CyberShark98** [PopGoesTheWza/swgoh-tb-sheets#6]
✖ USAGE QUESTIONS → Use these dedicated resources:
      Docs - [Instructions Manual](https://docs.google.com/document/d/1InDnFdYdlRDpejeiFkGi6HxMEWmBbfX_wAvWRf1MCME/edit?usp=sharing)
      Discord server - https://discord.gg/ywzJEaQ

✔ Enhancements → Be specific. Suggest implementation when possible.
✔ BUGS → ❤❤❤. Keep in mind some bugs may not be immediately fixable.

### Title (Put in field above)
Use the format: [version] Short description
i.e. [1.181011.0] On tab "Search Units" sort order is wrond

### Version
x.y.z

### Testcase
Provide a link to a copy of the TB Sheets if necessary

**Comment by PopGoesTheWza** [comment]
Fix is in testing and should be ready for next release.
