### ISSUE TITLE
[1.181011.0] SWGOH.help API password

### ISSUE THREAD

**Issue by DarkPhoenixSniper** [PopGoesTheWza/swgoh-tb-sheets#7]
✖ USAGE QUESTIONS → Use these dedicated resources:
      Docs - [Instructions Manual](https://docs.google.com/document/d/1InDnFdYdlRDpejeiFkGi6HxMEWmBbfX_wAvWRf1MCME/edit?usp=sharing)
      Discord server - https://discord.gg/ywzJEaQ

✔ Enhancements → Be specific. Suggest implementation when possible.
✔ BUGS → ❤❤❤. Keep in mind some bugs may not be immediately fixable.
### Steps to reproduce
swgoh.help api account password.  If password is in date format such as "June222018" or "July0404"
During the script signin, it turns it into a date using new date()

### Expected Result
should read that cell as text only...

### Actual Result
reads the input from cell as a date if in a date format for password

### Version
1.181011.0

### Testcase
Provide a link to a copy of the TB Sheets if necessary

**Comment by PopGoesTheWza** [comment]
Possible workaround:
- Select on "Meta" tab cell A18 (SwgohHelp password)
- Open the "Format" menu (top menu bar)
- Select "Number >" sub menu and select "Plain text"

Confirm if this solve the issue and the template will be updated with those settings.

**Comment by DarkPhoenixSniper** [comment]
CONFIRMED this resolves said issue with a password that is date format as mentioned.

I'm just trying to break things, as this was an issue in my own spreadsheets :)

**Comment by PopGoesTheWza** [comment]
Ready to ship with next release.
