### ISSUE TITLE
Incorporate platoon detection from pics via echobase's API

### ISSUE THREAD

**Issue by skiadas** [PopGoesTheWza/swgoh-tb-sheets#9]
The idea is that users should be able to provide us with the platoon screenshots. Then we could leverage this API to get platoon assignments to happen.

https://echobase.app/swagger-ui.html#!/screenshot-controller/uploadScreenshotUsingPOST

Possible ways for users to submit pictures:

- Have a new sheet to store screenshots in cells, then run a script.
- Use onEdit trigger to let users paste the screenshot somewhere in the existing platoons tab.
- Bring up a sidebar window and use normal html file upload system.
- Something else?

**Comment by PopGoesTheWza** [comment]
This issue will become obsolete when EA/CG release the new fixed and common platoons for all 6 phases
